name: API Tests ToDo Application

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installation des librairies
        run: npm install

      - name: Lancement du serveur
        run: |
          nohup node server.js > server.log 2>&1 &
          sleep 5

      - name: Installation de newman + HTML extra reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Lancement de newman
        run: |
          newman run "./postman/todo.postman_collection.json" \
          -e "./postman/todo.postman_environment.json" \
           -r htmlextra \
           --reporter-htmlextra-export "./postman/rapport.html"
      - name: upload HTML test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-report
          path: postman/rapportNewman.html
      - name: Add HTML report link
        run: |
          echo "### Rapport newman généré" >> $GITHUB_STEP_SUMMARY
          echo "Télécharger le rapport depuis la section artifact **Artifact ->newman-test-report**" >> $GITHUB_STEP_SUMMARY
